Rails6/alpha-blog/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

Rails6/alpha-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails6/alpha-blog/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

Rails6/alpha-blog/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles
  validates :username, presence: true, 
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum:  3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
                    
  has_secure_password
end

Rails6/alpha-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Rails6/alpha-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

Rails6/alpha-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end
  
end

Rails6/alpha-blog/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome #{@user.username}, you have succesfully sign into the app"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        
        @user = User.find(params[:id])
    end

    private

    def set_user
        @user = User.find(params[:id])
      end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

Rails6/alpha-blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails6/alpha-blog/app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10  text-white">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %><br/>
          <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow ronded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label" %><br/>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: " text-info" %>
    </div>
  </div>
</div>

Rails6/alpha-blog/app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create new Article</h1>
    <%= render 'form' %>
    
</div>

Rails6/alpha-blog/app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Articles listing page</h1>
  <%= link_to 'Create new article', new_article_path, class: "btn btn-outline-primary new-button-float" %>
  <a href=""></a>

  <div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
            <%= "By " +  article.user.username if article.user %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>

              <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete",  article_path(article), method: :delete, data: { confirm: "The article is going to be deleted, are you sure?" },  class: "btn btn-outline-danger" %>
            </div>
            <div class="card-footer text-muted">
             <small>Created <%= time_ago_in_words(article.created_at) %> ago, Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

Rails6/alpha-blog/app/views/articles/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Create new Article</h1>
    <%= render 'form' %>

</div>

Rails6/alpha-blog/app/views/articles/show.html.erb
<div class="container text-center mt-4">
  <h1><%= @article.title %></h1>
  <div class="row justify-content-md-center">
  <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
          <%= "By " +  @article.user.username if @article.user %>
      </div>
      <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>

          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete",  article_path(@article), method: :delete, data: { confirm: "The article is going to be deleted, are you sure?" },  class: "btn btn-outline-danger" %>
      </div>
      <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
      </div>
  </div>
  </div>
</div>

Rails6/alpha-blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
        <small>Copyright &copy; Your Website</small>
    </div>
</footer>

Rails6/alpha-blog/app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

Rails6/alpha-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Articles", articles_path, class: "dropdown-item" %>
            <%= link_to "New article",  new_article_path, class: "dropdown-item" %>
        </li>
        <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
</nav>

Rails6/alpha-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column page-content">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

Rails6/alpha-blog/app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

Rails6/alpha-blog/app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron text-center text-white align-middle">
    <h1 class="display-4">Hello, world!</h1>
    <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>
    <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %></p>
    </div>
</div>
<div id="page-content">

</div>

Rails6/alpha-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

Rails6/alpha-blog/app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10  text-white">
    <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label" %><br/>
          <div class="col-10">
          <%= f.text_field :username, class: "form-control shadow ronded", placeholder: "Enter a Username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %><br/>
          <div class="col-10">
            <%= f.email_field :email,  class: "form-control shadow rounded", placeholder: "Enter your email" %>
          </div>
        </div>

        <div class="form-group row">
            <%= f.label :password, class: "col-2 col-form-label" %><br/>
            <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter your password" %>
            </div>
        </div>
        
        <div class="form-group row justify-content-center">
          <%= f.submit "Sign up", class: "btn btn-outline-light btn-lg" %>
        </div>

      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: " text-info" %>
    </div>
  </div>
</div>

Rails6/alpha-blog/app/views/users/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Modify user info</h1>
    <%= render 'form' %>
    
</div>

Rails6/alpha-blog/app/views/users/new.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Sign Up</h1>
    <%= render 'form' %>

</div>